name: Quotio
options:
  bundleIdPrefix: com.qqxluca
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: "2.8.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "0.7.7"
    CURRENT_PROJECT_VERSION: "0.7.7"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGN_ENTITLEMENTS: ""

targets:
  Quotio:
    type: application
    platform: macOS
    sources:
      - path: Quotio
        excludes:
          - "**/.DS_Store"
          - "**/*.md"
          - "**/*.mdx"
      - path: scripts
        excludes:
          - "**/*.md"
    settings:
      base:
        INFOPLIST_FILE: Quotio/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.qqxluca.Quotio
        PRODUCT_NAME: Quotio
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: "YES"
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: "YES"
        CODE_SIGN_ENTITLEMENTS: Quotio/Quotio.entitlements
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    dependencies:
      - package: Sparkle
